### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'

### ISSUE THREAD

**Issue by KiAlexander** [kaituoxu/Conv-TasNet#18]
like WSJ0-mix, I make some micture from Librispeech in which tr, cv and tt dir contain 20000, 5000,3000 respectively . But I try to run your scripts, something wrong happened. Can you help me to figure it out? Thx.

And  the key error of the train log is as follows:
"Training...
Traceback (most recent call last):
  File "/home/yjm/Conv-TasNet/egs/LibriSpeech/../../src/train.py", line 145, in <module>
    main(args)
  File "/home/yjm/Conv-TasNet/egs/LibriSpeech/../../src/train.py", line 139, in main
    solver.train()
  File "/home/yjm/Conv-TasNet/src/solver.py", line 76, in train
    tr_avg_loss = self._run_one_epoch(epoch)
  File "/home/yjm/Conv-TasNet/src/solver.py", line 178, in _run_one_epoch
    estimate_source = self.model(padded_mixture)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yjm/Conv-TasNet/src/conv_tasnet.py", line 54, in forward
    est_source = self.decoder(mixture_w, est_mask)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yjm/Conv-TasNet/src/conv_tasnet.py", line 141, in forward
    est_source = overlap_and_add(est_source, self.L//2) # M x C x T
  File "/home/yjm/Conv-TasNet/src/utils.py", line 45, in overlap_and_add
    result.index_add_(-2, frame, subframe_signal)
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'"

**Comment by mpariente** [comment]
Making a dataset from Librispeech is a great initiative !  


This error is weird because `frame` and `subframe_signal` are supposed to be on the same device.. What is your `torch` version? 
Can you try adding this [here](https://github.com/kaituoxu/Conv-TasNet/blob/master/src/utils.py#L41) 
`frame = frame.to(subframe_signal.device)` ? 
It will transfer the `frame` to the same device as `subframe_signal`.

**Comment by KiAlexander** [comment]
thx a lot!

**Comment by mpariente** [comment]
By the way, would you consider sharing such a dataset recipe? It would be great for research purpose!

**Comment by KiAlexander** [comment]
maybe it‘s better to see [here](https://github.com/mindslab-ai/voicefilter) how to prepare data based on librispeech
